ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080
db:
  jdbcUrl: "jdbc:postgresql://localhost:5433/hvalfangst_db?user=glossy&password=yellauyellau"
flyway:
  migrationPath: "classpath:common/db/migration"
jwt:
  secret: "MountedKubernetesSecretDerivedFromVault"
  issuer: "http://0.0.0.0:8080/users"
  audience: "http://0.0.0.0:8080/music"