ktor:
    application:
        modules:
            - ApplicationKt.module
    deployment:
        port: 8080
db:
  jdbcUrl: "jdbc:postgresql://localhost:5433/hvalfangst_db?user=glossy&password=yellauyellau"